// Based on https://github.com/webpack/webpack/blob/master/lib/index.js

// eslint-disable-next-line import/prefer-default-export
export const fakeWebpack = {
  AutomaticPrefetchPlugin: Object,
  BannerPlugin: Object,
  Cache: Object,
  Compilation: Object,
  ContextExclusionPlugin: Object,
  ContextReplacementPlugin: Object,
  DefinePlugin: Object,
  DelegatedPlugin: Object,
  Dependency: Object,
  DllPlugin: Object,
  DllReferencePlugin: Object,
  EntryPlugin: Object,
  EnvironmentPlugin: Object,
  EvalDevToolModulePlugin: Object,
  EvalSourceMapDevToolPlugin: Object,
  ExternalsPlugin: Object,
  Generator: Object,
  HotModuleReplacementPlugin: Object,
  IgnorePlugin: Object,
  JavascriptModulesPlugin: Object,
  LibManifestPlugin: Object,
  LibraryTemplatePlugin: Object,
  LoaderOptionsPlugin: Object,
  LoaderTargetPlugin: Object,
  Module: Object,
  ModuleFilenameHelpers: Object,
  NoEmitOnErrorsPlugin: Object,
  NormalModule: Object,
  NormalModuleReplacementPlugin: Object,
  Parser: Object,
  PrefetchPlugin: Object,
  ProgressPlugin: Object,
  ProvidePlugin: Object,
  RuntimeGlobals: Object,
  RuntimeModule: Object,
  SingleEntryPlugin: Object,
  SetVarTemplatePlugin: Object,
  SourceMapDevToolPlugin: Object,
  Stats: Object,
  Template: Object,
  UmdTemplatePlugin: Object,
  WatchIgnorePlugin: Object,
  cache: {
    MemoryCachePlugin: Object,
  },
  ids: {
    ChunkModuleIdRangePlugin: Object,
    NaturalModuleIdsPlugin: Object,
    OccurrenceModuleIdsPlugin: Object,
    NamedModuleIdsPlugin: Object,
    DeterministicModuleIdsPlugin: Object,
    NamedChunkIdsPlugin: Object,
    OccurrenceChunkIdsPlugin: Object,
    HashedModuleIdsPlugin: Object,
  },
  javascript: {
    JavascriptModulesPlugin: Object,
  },
  optimize: {
    AggressiveMergingPlugin: Object,
    AggressiveSplittingPlugin: Object,
    LimitChunkCountPlugin: Object,
    MinChunkSizePlugin: Object,
    ModuleConcatenationPlugin: Object,
    RuntimeChunkPlugin: Object,
    SideEffectsFlagPlugin: Object,
    SplitChunksPlugin: Object,
  },
  web: {
    FetchCompileWasmPlugin: Object,
    JsonpTemplatePlugin: Object,
  },
  webworker: {
    WebWorkerTemplatePlugin: Object,
  },
  node: {
    NodeEnvironmentPlugin: Object,
    NodeTemplatePlugin: Object,
    ReadFileCompileWasmPlugin: Object,
  },
  wasm: {
    AsyncWebAssemblyModulesPlugin: Object,
  },
  debug: {
    ProfilingPlugin: Object,
  },
  util: {
    createHash: Object,
    comparators: Object,
    serialization: Object,
  },
};
