name: ci

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
        include:
          - node-version: 20.x
            codecov: true
    name: Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run compile
      - run: npm run component
      - run: npm run depcheck
      - run: npm run depcheck-json
      - run: npm run lint
      - run: npm run prettier-check
      - run: npm run test-coverage

      - uses: codecov/codecov-action@v3
        if: matrix.codecov
        with:
          file: ./coverage/coverage.lcov
          name: codecov-umbrella
          fail_ci_if_error: false
